In [1]:
## Matrix multiplikation
import numpy as np

In [2]:
#Create a matrix with 2 rows and 2 columns
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

#Multiply the two matrices
matrix3 = np.dot(matrix1, matrix2)

#Print the result
print("---- Matrix 1 ----")
print(matrix1)
print("---- Matrix 2 ----")
print(matrix2)
print("---- Matrix 3 ----")
print(matrix3)

---- Matrix 1 ----
[[1 2]
 [3 4]]
---- Matrix 2 ----
[[5 6]
 [7 8]]
---- Matrix 3 ----
[[19 22]
 [43 50]]


In [3]:
# Define the sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
# Initial weights
w1_1 = 0.9
w1_2 = 0.2
w2_1 = 0.3
w2_2 = 0.8

In [5]:
# Create a matrix with 2 rows and 2 columns
matrix_W = np.array([
    [w1_1, w2_1],
    [w1_2,w2_2]
    ])
matrix_I = np.array([1,0.5])
# Calculare W * I
matrix_X = np.dot(matrix_W, matrix_I)

# Multiply all elements with the sigmoid function
matrix_X = sigmoid(matrix_X)

# Output
print("---- Matrix W ----")
print(matrix_W)
print("---- Matrix I ----")
print(matrix_I)
print("---- Matrix X ----")
print(matrix_X)

---- Matrix W ----
[[0.9 0.3]
 [0.2 0.8]]
---- Matrix I ----
[1.  0.5]
---- Matrix X ----
[0.7407749  0.64565631]


In [6]:
# Dreischichtiges Netz
matrix_I = np.array([0.9,0.1,0.8])
matrix_W = np.array([[0.9,0.3,0.4],
                    [0.2,0.8,0.2],
                    [0.1,0.5,0.6]])
matrix_X_S1 = np.dot(matrix_W, matrix_I)
print("---- Matrix X S1 ----")
print(matrix_X_S1)
matrix_X_S1 = sigmoid(matrix_X_S1)
print("---- Matrix X S1 Sigmoid ----")
print(matrix_X_S1)

---- Matrix X S1 ----
[1.16 0.42 0.62]
---- Matrix X S1 Sigmoid ----
[0.76133271 0.60348325 0.65021855]


In [7]:
# Gewichte von Schicht 2 zu Schicht 3
# [[W11,W12,W13]
# [W21,W22,W23]
# [W31,W32,W33]]

matrix_W_S2 = np.array([[0.3,0.7,0.5],
                        [0.6,0.5,0.2],
                        [0.8,0.1,0.9]])
matrix_X_S2 = np.dot(matrix_W_S2, matrix_X_S1)
print("---- Matrix X S2 ----")
print(matrix_X_S2)
matrix_X_S2 = sigmoid(matrix_X_S2)
print("---- Matrix X S2 Sigmoid ----")
print(matrix_X_S2)

---- Matrix X S2 ----
[0.97594736 0.88858496 1.25461119]
---- Matrix X S2 Sigmoid ----
[0.72630335 0.70859807 0.77809706]


In [8]:
## Backpropagation
print(matrix_W_S2)
print(matrix_W_S2.T)

[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
[[0.3 0.6 0.8]
 [0.7 0.5 0.1]
 [0.5 0.2 0.9]]
